### ISSUE TITLE
After few hours of running bot died on connection status

### ISSUE THREAD

**Issue by TrueCarry** [joshuaferrara/node-csgo#10]
I'm not sure why GCConnectionStatus is undefined, but it doesn't appearing in CSGO scope.

``` bash
/home/csgo/node_modules/csgo/index.js:121
    case CSGO.GCConnectionStatus.GCConnectionStatus_HAVE_SESSION:
                                ^
TypeError: Cannot read property 'GCConnectionStatus_HAVE_SESSION' of undefined
    at CSGOClient.gcClientConnectionStatus (/home/csgo/node_modules/csgo/index.js:121:33)
    at SteamClient.fromGC (/home/csgo/node_modules/csgo/index.js:32:30)
    at SteamClient.emit (events.js:118:17)
    at SteamClient.handlers.(anonymous function) (/home/csgo/node_modules/steam/lib/handlers/game_coordinator.js:59:13)
    at SteamClient._netMsgReceived (/home/csgo/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/home/csgo/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/home/csgo/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/csgo/node_modules/steam/lib/connection.js:50:8)
```

**Comment by agpmilli** [comment]
Hi!

Just happened to have the same issue. Is there something specific to do to fix it?

Thanks!

**Comment by thecatontheflat** [comment]
Happened to me as well
