### ISSUE TITLE
playerProfileRequest mainly returns null and readCString error

### ISSUE THREAD

**Issue by LegendNed** [joshuaferrara/node-csgo#78]
Since the start of using the 'package', I've been trying to recieve player profile information; however, all requests no matter what valid `accoundID` provided returns `null` for the majority of the fields:
```
{
  "request_id": null,
  "account_profiles": [
    {
      "account_id": 396346719,
      "ongoingmatch": null,
      "global_stats": null,
      "penalty_seconds": null,
      "penalty_reason": null,
      "vac_banned": null,
      "ranking": null,
      "commendation": {
        "cmd_friendly": 19,
        "cmd_teaching": 16,
        "cmd_leader": 18
      },
      "medals": {
        "medal_team": null,
        "medal_combat": null,
        "medal_weapon": null,
        "medal_global": null,
        "medal_arms": null,
        "display_items_defidx": [
          4674,
          970,
          1367
        ],
        "featured_display_item_defidx": 4674
      },
      "my_current_event": null,
      "my_current_event_teams": [],
      "my_current_team": null,
      "my_current_event_stages": [],
      "survey_vote": null,
      "activity": null,
      "player_level": 14,
      "player_cur_xp": 327681231,
      "player_xp_bonus_flags": null
    }
  ]
}
```

The logs return:
```
13 Dec 23:37:01 - Launching CS:GO
13 Dec 23:37:03 - Sending ClientHello
13 Dec 23:37:03 - CS:GO fromGC: 4004
13 Dec 23:37:03 - Received client welcome.
13 Dec 23:37:03 - Sending player profile request
13 Dec 23:37:04 - CS:GO fromGC: 9173
13 Dec 23:37:04 - CS:GO fromGC: 9128
13 Dec 23:37:04 - Received player profile
```

Can confirm CS GO is running, as it established a successful connection and: 
![ur5U](https://user-images.githubusercontent.com/46972221/102026519-35af4600-3d96-11eb-91b9-1001d52e8c50.png)

____

In addition, I've had the client crash to a random error:
```
/root/**********/node_modules/csgo/helpers/VDF.js:28
            var name = buffer.readCString();
                              ^

TypeError: buffer.readCString is not a function
    at Object.exports.decode (/root/**********/node_modules/csgo/helpers/VDF.js:28:31)
    at CSGOClient.handlers.<computed> (/root/**********/node_modules/csgo/handlers/rich_presence.js:44:20)
    at SteamClient.<anonymous> (/root/**********/node_modules/csgo/index.js:50:30)
    at SteamClient.emit (events.js:326:22)
    at SteamClient._netMsgReceived (/root/**********/node_modules/steam/lib/steam_client.js:175:10)
    at SteamClient.handlers.<computed> (/root/**********/node_modules/steam/lib/steam_client.js:262:10)
    at SteamClient._netMsgReceived (/root/**********/node_modules/steam/lib/steam_client.js:160:26)
    at Connection.emit (events.js:314:20)
    at Connection._readPacket (/root/**********/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

Can provide more information if needed!

**Comment by patrykczubek** [comment]
Did you find a fix?

**Comment by Forge-Media** [comment]
What was the solution to `var name = buffer.readCString();` 
TypeError: buffer.readCString is not a function

I've stated to have this same issue?

**Comment by ramonwanderley** [comment]
@LegendNed, were you able to solve this problem? I'm trying to get the same answer. Players who have rank are coming with the value null.

**Comment by LegendNed** [comment]
> @LegendNed, were you able to solve this problem? I'm trying to get the same answer. Players who have rank are coming with the value null.

Quite a time ago, however, if I remember correctly there was no proper solution, some user ranks were not retrieved at all returning the value as null
